### ISSUE TITLE
[Feature Request] Enhance Pointf and Point classes

### ISSUE THREAD

**Issue by lucasstarsz** [lucasstarsz/FastJ#9]
## Is your feature request related to a problem? Please describe.
The `Point` and `Pointf` classes are FastJ's choice of weaponry when it comes to vector math. As such, there are many things to consider adding.

## What should the solution be like?
Several methods revolving around vectors should be implemented, such as:
- [x] Magnitude
- [x] Square Magnitude
- [x] Normalization
- [x] Dot Product
- [x] Cross Product
- [x] Vector Rotation
- [x] Angle (between two vectors)

The following are of less importance, but it is also desirable to create abstractions to allow working with certain AWT types:
- [x] Conversion to `java.awt.Dimension`

~~And last but not least, I would like to achieve some more major improvements to the system as a whole:~~
~~- Abstract `Point`/`Pointf` to an interface, allowing the following:~~
~~- [ ] Immutable versions of `Pointf` and `Point` classes~~
~~- [ ] Reusability and a better guarantee that they will mesh together reliably in the future.~~

**The above will be considered in a later issue. For now, it's out of the scope for completing smaller projects within the engine.**

If you find more methods to be necessary, please leave a comment.
Progress of these features will be tracked in the `math-improvement` branch.

**Comment by nt314p** [comment]
Suggested methods:
- [ ] Square magnitude
- [ ] Rotate vector
- [ ] Vector angle

Another point: since cross product is not defined with 2d vectors, there are several other implementations you can use, each with pros and cons (see https://stackoverflow.com/questions/243945/calculating-a-2d-vectors-cross-product).

**Comment by lucasstarsz** [comment]
> Suggested methods:
> 
> * [ ]  Square magnitude
> * [ ]  Rotate vector
> * [ ]  Vector angle

Seems I forgot about those. I'll add them to the list right away!

> Another point: since cross product is not defined with 2d vectors, there are several other implementations you can use, each with pros and cons (see https://stackoverflow.com/questions/243945/calculating-a-2d-vectors-cross-product).

I remember reading over that article a few months back. I'd likely go with the scalar representation over the vector representation -- however, the vector representation might be useful for displaying the perpendicular version of a vector. We'll see how that goes.
